### ISSUE TITLE
Sound question

### ISSUE THREAD

**Issue by ssommelet21** [kevinshen56714/create-react-phaser3-app#6]
Hello Kevin,

Thank you for this nice demo.
Just a little question. Imagine i do some change in the "HelloWorldScene.ts" :

...

  preload() {
    // this.load.setBaseURL('https://labs.phaser.io')
    this.load.image("logo", "/assets/sprites/phaser3-logo.png");
    this.load.image("red", "/assets/particles/red.png");
    this.load.audio("music", "/Sound/blaster.mp3");
  }

  create() {
    this.music = this.add.audio("music"); // doesn't work
    this.music.play();  // of course doesn't work
    this.createEmitter();
  }

...

The error is : "Uncaught TypeError: this.add.audio is not a function"

I can't figure out what is wrong for making the sound working.
Your help is appreciated

**Comment by kevinshen56714** [comment]
Hi!

I've never added sound but it seems like you add sound to the sound manager of a scene, not to the scene itself. For example, `this.sound.add("music")`.

Refs: 
1. https://rexrainbow.github.io/phaser3-rex-notes/docs/site/audio/#sound-instance
2. https://photonstorm.github.io/phaser3-docs/Phaser.Sound.BaseSoundManager.html#add__anchor

Let me know if it works!

**Comment by ssommelet21** [comment]
Thank you very much, it works ;-)
